environment:
  nodejs_version: "14"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

before_build:
build: off
after_build:

before_test:
  - node --version
  - npm --version

test_script:
  - npx mocha

after_test:

